### Get all students
GET http://localhost:3000/students

### Get student by ID
GET http://localhost:3000/students/id/S002

### Get student by ID not found
GET http://localhost:3000/students/id/22120415

### Get students by name
GET http://localhost:3000/students/name?name=GROUP API TEST

### Add new student
POST http://localhost:3000/students
Content-Type: application/json

{
  "id": "22120413",
  "name": "GROUP API TEST",
  "dob": "2025-03-12",
  "gender": "Nam",
  "faculty": "L",
  "academicYear": 2023,
  "program": "Dai Tra",
  "permanentAddress": {
    "city": "TP.HCM",
    "district": "Quận 1",
    "ward": "Phường A",
    "street": "123 Đường ABC"
  },
  "temporaryAddress": {
    "city": "TP.HCM",
    "district": "Quận 3",
    "ward": "Phường B",
    "street": "456 Đường DEF"
  },
  "email": "group19apitest@student.edu.vn",
  "phone": "0123456789",
  "status": "DH",
  "identityDocument": {
    "type": "NewIdentityCard",
    "issuedDate": "2015-06-15T00:00:00Z",
    "issuedPlace": "TP.HCM",
    "expiredDate": "2026-06-15T00:00:00Z"
  },
  "nationality": "VN"
}

### Add existing student
POST http://localhost:3000/students
Content-Type: application/json

{
  "id": "22120413",
  "name": "GROUP API TEST",
  "dob": "2025-03-12",
  "gender": "Nam",
  "faculty": "L",
  "academicYear": 2023,
  "program": "Dai Tra",
  "permanentAddress": {
    "city": "TP.HCM",
    "district": "Quận 1",
    "ward": "Phường A",
    "street": "123 Đường ABC"
  },
  "temporaryAddress": {
    "city": "TP.HCM",
    "district": "Quận 3",
    "ward": "Phường B",
    "street": "456 Đường DEF"
  },
  "email": "group19apitest@student.edu.vn",
  "phone": "0123456789",
  "status": "DH",
  "identityDocument": {
    "type": "NewIdentityCard",
    "issuedDate": "2015-06-15T00:00:00Z",
    "issuedPlace": "TP.HCM",
    "expiredDate": "2026-06-15T00:00:00Z"
  },
  "nationality": "VN"
}

### Add new student with invalid email
POST http://localhost:3000/students
Content-Type: application/json

{
  "id": "22120414",
  "name": "GROUP API TEST",
  "dob": "2025-03-12",
  "gender": "Nam",
  "faculty": "L",
  "academicYear": 2023,
  "program": "Dai Tra",
  "permanentAddress": {
    "city": "TP.HCM",
    "district": "Quận 1",
    "ward": "Phường A",
    "street": "123 Đường ABC"
  },
  "temporaryAddress": {
    "city": "TP.HCM",
    "district": "Quận 3",
    "ward": "Phường B",
    "street": "456 Đường DEF"
  },
  "email": "group19apitest@example.com",
  "phone": "0123456789",
  "status": "DH",
  "identityDocument": {
    "type": "NewIdentityCard",
    "issuedDate": "2015-06-15T00:00:00Z",
    "issuedPlace": "TP.HCM",
    "expiredDate": "2026-06-15T00:00:00Z"
  },
  "nationality": "VN"
}

### Add new student with invalid phone number
POST http://localhost:3000/students
Content-Type: application/json

{
  "id": "22120415",
  "name": "GROUP API TEST",
  "dob": "2025-03-12",
  "gender": "Nam",
  "faculty": "L",
  "academicYear": 2023,
  "program": "Dai Tra",
  "permanentAddress": {
    "city": "TP.HCM",
    "district": "Quận 1",
    "ward": "Phường A",
    "street": "123 Đường ABC"
  },
  "temporaryAddress": {
    "city": "TP.HCM",
    "district": "Quận 3",
    "ward": "Phường B",
    "street": "456 Đường DEF"
  },
  "email": "group19apitest@student.edu.vn",
  "phone": "012345689",
  "status": "DH",
  "identityDocument": {
    "type": "NewIdentityCard",
    "issuedDate": "2015-06-15T00:00:00Z",
    "issuedPlace": "TP.HCM",
    "expiredDate": "2026-06-15T00:00:00Z"
  },
  "nationality": "VN"
}

### Delete student
DELETE http://localhost:3000/students/22120413