### Import Students in JSON Test
POST http://localhost:3000/utils/students/json
Content-Type: application/json

{
    "students": "[{\"id\": \"22120413\", \"name\": \"Tuong Nguyen\", \"email\": \"tuong.nguyen@example.com\"}, {\"id\": \"2\", \"name\": \"Vu Nguyen\", \"email\": \"vu.nguyen@example.com\"}]"
}


### Export Students in JSON Test
GET http://localhost:3000/utils/students/json

### Import Students in XML Test
POST http://localhost:3000/utils/students/xml
Content-Type: application/json

{
    "students": "<students><student><id>22120413</id><name>Tuong Nguyen</name><email>tuong.nguyen@example.com</email></student><student><id>2</id><name>Vu Nguyen</name><email>vu.nguyen@example.com</email></student></students>"
}

### Export Students in XML Test
GET http://localhost:3000/utils/students/xml